.\" Copyright (c) 2001 Mark R V Murray
.\" Copyright (c) 2001-2003 Networks Associates Technology, Inc.
.\" Copyright (c) 2009 Gleb Kurtsou
.\" All rights reserved.
.\"
.\" This software was developed for the FreeBSD Project by ThinkSec AS and
.\" NAI Labs, the Security Research Division of Network Associates, Inc.
.\" under DARPA/SPAWAR contract N66001-01-C-8035 ("CBOSS"), as part of the
.\" DARPA CHATS research program.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd December 1, 2009
.Dt PAM_PEFS 8
.Os
.Sh NAME
.Nm pam_pefs
.Nd pefs PAM module
.Sh SYNOPSIS
.Op Ar service-name
.Ar module-type
.Ar control-flag
.Pa pam_pefs
.Op Ar options
.Sh DESCRIPTION
The
pefs
authentication service module for PAM,
.Nm
provides functionality for two PAM categories:
authentication
and session management.
In terms of the
.Ar module-type
parameter, they are the
.Dq Li auth
and
.Dq Li session
features.
.Pp
Module expects pefs file system to be mounted on user home directory
and fails otherwise.
.Ss Pefs Authentication Module
The
pefs
authentication component
provides a function to verify the identity of a user
.Pq Fn pam_sm_authenticate ,
by prompting the user for a passphrase and verifying that it exists in
pefs key chain database.
.Pp
The following options may be passed to the authentication module:
.Bl -tag -width ".Cm use_first_pass"
.It Cm use_first_pass
If the authentication module
is not the first in the stack,
and a previous module
obtained the user's password,
that password is used
to authenticate the user.
If this fails,
the authentication module returns failure
without prompting the user for a password.
This option has no effect
if the authentication module
is the first in the stack,
or if no previous modules
obtained the user's password.
.It Cm try_first_pass
This option is similar to the
.Cm use_first_pass
option,
except that if the previously obtained password fails,
the user is prompted for another password.
.It Cm ignore_missing
Accept any passphrase provided by the user.
This option is used not to authenticate user, but to preserve keys that
should be added to pefs file system by session management module.
Option is incompatible with
.Cm try_first_pass
option and should be used with
.Cm use_first_pass
option.
.It Cm delkeys
Remove keys at the end of last session.
Module tracks the number of concurrent sessions, removing all keys from
file system when session count reaches zero.
.El
.Ss Pefs Session Management Module
The
pefs
session management component
provides functions to initiate
.Pq Fn pam_sm_open_session
and terminate
.Pq Fn pam_sm_close_session
sessions.
The
.Fn pam_sm_open_session
function adds key or key chain decrypted during the authentication phase
to the pefs file system mounted on user home directory.
.Sh FILES
.Bl -tag -width ".Pa $HOME/.pefs.conf" -compact
.It Pa $HOME/.pefs.conf
pefs configuration file
.It Pa $HOME/.pefs.db
pefs key chain database file
.El
.Sh SEE ALSO
.Xr pam.conf 5 ,
.Xr pam 8
.Xr pefs 8
.Sh AUTHORS
The
.Nm
module was written by
.An -nosplit
.An "Gleb Kurtsou" Aq gk@FreeBSD.org .
.Sh BUGS
.Fn pam_sm_close_session
function
doesn't delete keys added during by
.Fn pam_sm_open_session .
