#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: gssd
# REQUIRE: root
# KEYWORD: nojail shutdown

. /etc/rc.subr

name=gssd
desc="Generic Security Services Daemon"
rcvar=gssd_enable
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
