/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $FreeBSD$
 * created from	FreeBSD
 */

#define	MACH_SYS_mach_reply_port	26
#define	MACH_SYS_mach_thread_self_trap	27
#define	MACH_SYS_mach_task_self_trap	28
#define	MACH_SYS_mach_host_self_trap	29
#define	MACH_SYS_mach_msg_trap	31
#define	MACH_SYS_mach_msg_overwrite_trap	32
#define	MACH_SYS_mach_semaphore_signal_trap	33
#define	MACH_SYS_mach_semaphore_signal_all_trap	34
#define	MACH_SYS_mach_semaphore_signal_thread_trap	35
#define	MACH_SYS_mach_semaphore_wait_trap	36
#define	MACH_SYS_mach_semaphore_wait_signal_trap	37
#define	MACH_SYS_mach_semaphore_timedwait_trap	38
#define	MACH_SYS_mach_semaphore_timedwait_signal_trap	39
#define	MACH_SYS_mach_init_process	41
#define	MACH_SYS_mach_map_fd	43
#define	MACH_SYS_mach_task_for_pid	45
#define	MACH_SYS_mach_pid_for_task	46
#define	MACH_SYS_mach_macx_swapon	48
#define	MACH_SYS_mach_macx_swapoff	49
#define	MACH_SYS_mach_macx_triggers	51
#define	MACH_SYS_mach_swtch_pri	59
#define	MACH_SYS_mach_swtch	60
#define	MACH_SYS_mach_syscall_thread_switch	61
#define	MACH_SYS_mach_clock_sleep_trap	62
#define	MACH_SYS_mach_timebase_info	89
#define	MACH_SYS_mach_wait_until	90
#define	MACH_SYS_mach_timer_create	91
#define	MACH_SYS_mach_timer_destroy	92
#define	MACH_SYS_mach_timer_arm	93
#define	MACH_SYS_mach_timer_cancel	94
#define	MACH_SYS_mach_get_time_base_info	95
#define	MACH_SYS_MAXSYSCALL	128
