/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $FreeBSD$
 * created from	FreeBSD
 */

#include "opt_ntp.h"
#include <sys/cdefs.h>
#include <sys/types.h>
#include <sys/param.h>
#include <sys/systm.h>
#include <sys/signal.h>
#include <sys/mount.h>
#include <sys/poll.h>
#include <sys/sysent.h>
#include <sys/sysproto.h>
#include <vm/vm.h>
#include <compat/mach/mach_types.h>
#include <compat/mach/mach_message.h>
#include <compat/mach/mach_clock.h>
#include <compat/mach/mach_port.h>
#include <compat/mach/mach_proto.h>

#define AS(name) (sizeof(struct name) / sizeof(register_t))

/* The casts are bogus but will do for now. */
struct sysent mach_sysent[] = {
#if defined(_KERNEL_OPT)
#endif
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 0 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 1 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 2 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 3 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 4 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 5 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 6 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 7 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 8 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 9 = nosys */
	{ AS(_kernelrpc_mach_vm_allocate_trap_args), (sy_call_t *)sys__kernelrpc_mach_vm_allocate_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 10 = _kernelrpc_mach_vm_allocate_trap */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 11 = nosys */
	{ AS(_kernelrpc_mach_vm_deallocate_trap_args), (sy_call_t *)sys__kernelrpc_mach_vm_deallocate_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 12 = _kernelrpc_mach_vm_deallocate_trap */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 13 = nosys */
	{ AS(_kernelrpc_mach_vm_protect_trap_args), (sy_call_t *)sys__kernelrpc_mach_vm_protect_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 14 = _kernelrpc_mach_vm_protect_trap */
	{ AS(_kernelrpc_mach_vm_map_trap_args), (sy_call_t *)sys__kernelrpc_mach_vm_map_trap, AUE_MMAP, NULL, 0, 0, 0, SY_THR_STATIC },	/* 15 = _kernelrpc_mach_vm_map_trap */
	{ AS(_kernelrpc_mach_port_allocate_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_allocate_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 16 = _kernelrpc_mach_port_allocate_trap */
	{ AS(_kernelrpc_mach_port_destroy_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_destroy_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 17 = _kernelrpc_mach_port_destroy_trap */
	{ AS(_kernelrpc_mach_port_deallocate_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_deallocate_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 18 = _kernelrpc_mach_port_deallocate_trap */
	{ AS(_kernelrpc_mach_port_mod_refs_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_mod_refs_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 19 = _kernelrpc_mach_port_mod_refs_trap */
	{ AS(_kernelrpc_mach_port_move_member_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_move_member_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 20 = _kernelrpc_mach_port_move_member_trap */
	{ AS(_kernelrpc_mach_port_insert_right_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_insert_right_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 21 = _kernelrpc_mach_port_insert_right_trap */
	{ AS(_kernelrpc_mach_port_insert_member_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_insert_member_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 22 = _kernelrpc_mach_port_insert_member_trap */
	{ AS(_kernelrpc_mach_port_extract_member_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_extract_member_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 23 = _kernelrpc_mach_port_extract_member_trap */
	{ AS(_kernelrpc_mach_port_construct_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_construct_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 24 = _kernelrpc_mach_port_construct_trap */
	{ AS(_kernelrpc_mach_port_destruct_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_destruct_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 25 = _kernelrpc_mach_port_destruct_trap */
	{ 0, (sy_call_t *)sys_mach_reply_port, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 26 = mach_reply_port */
	{ 0, (sy_call_t *)sys_mach_thread_self_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 27 = mach_thread_self_trap */
	{ 0, (sy_call_t *)sys_mach_task_self_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 28 = mach_task_self_trap */
	{ 0, (sy_call_t *)sys_mach_host_self_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 29 = mach_host_self_trap */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 30 = nosys */
	{ AS(mach_msg_trap_args), (sy_call_t *)sys_mach_msg_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 31 = mach_msg_trap */
	{ AS(mach_msg_overwrite_trap_args), (sy_call_t *)sys_mach_msg_overwrite_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 32 = mach_msg_overwrite_trap */
	{ AS(mach_semaphore_signal_trap_args), (sy_call_t *)sys_mach_semaphore_signal_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 33 = mach_semaphore_signal_trap */
	{ AS(mach_semaphore_signal_all_trap_args), (sy_call_t *)sys_mach_semaphore_signal_all_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 34 = mach_semaphore_signal_all_trap */
	{ AS(mach_semaphore_signal_thread_trap_args), (sy_call_t *)sys_mach_semaphore_signal_thread_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 35 = mach_semaphore_signal_thread_trap */
	{ AS(mach_semaphore_wait_trap_args), (sy_call_t *)sys_mach_semaphore_wait_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 36 = mach_semaphore_wait_trap */
	{ AS(mach_semaphore_wait_signal_trap_args), (sy_call_t *)sys_mach_semaphore_wait_signal_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 37 = mach_semaphore_wait_signal_trap */
	{ AS(mach_semaphore_timedwait_trap_args), (sy_call_t *)sys_mach_semaphore_timedwait_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 38 = mach_semaphore_timedwait_trap */
	{ AS(mach_semaphore_timedwait_signal_trap_args), (sy_call_t *)sys_mach_semaphore_timedwait_signal_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 39 = mach_semaphore_timedwait_signal_trap */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 40 = nosys */
	{ AS(_kernelrpc_mach_port_guard_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_guard_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 41 = _kernelrpc_mach_port_guard_trap */
	{ AS(_kernelrpc_mach_port_unguard_trap_args), (sy_call_t *)sys__kernelrpc_mach_port_unguard_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 42 = _kernelrpc_mach_port_unguard_trap */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 43 = obsolete { */
	{ AS(mach_task_name_for_pid_args), (sy_call_t *)sys_mach_task_name_for_pid, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 44 = mach_task_name_for_pid */
	{ AS(mach_task_for_pid_args), (sy_call_t *)sys_mach_task_for_pid, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 45 = mach_task_for_pid */
	{ AS(mach_pid_for_task_args), (sy_call_t *)sys_mach_pid_for_task, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 46 = mach_pid_for_task */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 47 = nosys */
	{ AS(mach_macx_swapon_args), (sy_call_t *)sys_mach_macx_swapon, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 48 = mach_macx_swapon */
	{ AS(mach_macx_swapoff_args), (sy_call_t *)sys_mach_macx_swapoff, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 49 = mach_macx_swapoff */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 50 = nosys */
	{ AS(mach_macx_triggers_args), (sy_call_t *)sys_mach_macx_triggers, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 51 = mach_macx_triggers */
	{ AS(mach_macx_backing_store_suspend_args), (sy_call_t *)sys_mach_macx_backing_store_suspend, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 52 = mach_macx_backing_store_suspend */
	{ AS(mach_macx_backing_store_recovery_args), (sy_call_t *)sys_mach_macx_backing_store_recovery, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 53 = mach_macx_backing_store_recovery */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 54 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 55 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 56 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 57 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 58 = nosys */
	{ AS(mach_swtch_pri_args), (sy_call_t *)sys_mach_swtch_pri, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 59 = mach_swtch_pri */
	{ 0, (sy_call_t *)sys_mach_swtch, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 60 = mach_swtch */
	{ AS(mach_syscall_thread_switch_args), (sy_call_t *)sys_mach_syscall_thread_switch, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 61 = mach_syscall_thread_switch */
	{ AS(mach_clock_sleep_trap_args), (sy_call_t *)sys_mach_clock_sleep_trap, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 62 = mach_clock_sleep_trap */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 63 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 64 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 65 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 66 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 67 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 68 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 69 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 70 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 71 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 72 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 73 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 74 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 75 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 76 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 77 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 78 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 79 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 80 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 81 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 82 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 83 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 84 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 85 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 86 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 87 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 88 = nosys */
	{ AS(mach_timebase_info_args), (sy_call_t *)sys_mach_timebase_info, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 89 = mach_timebase_info */
	{ AS(mach_wait_until_args), (sy_call_t *)sys_mach_wait_until, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 90 = mach_wait_until */
	{ 0, (sy_call_t *)sys_mk_timer_create, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 91 = mk_timer_create */
	{ AS(mk_timer_destroy_args), (sy_call_t *)sys_mk_timer_destroy, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 92 = mk_timer_destroy */
	{ AS(mk_timer_arm_args), (sy_call_t *)sys_mk_timer_arm, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 93 = mk_timer_arm */
	{ AS(mk_timer_cancel_args), (sy_call_t *)sys_mk_timer_cancel, AUE_NULL, NULL, 0, 0, 0, SY_THR_STATIC },	/* 94 = mk_timer_cancel */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 95 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 96 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 97 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 98 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 99 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 100 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 101 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 102 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 103 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 104 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 105 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 106 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 107 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 108 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 109 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 110 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 111 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 112 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 113 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 114 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 115 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 116 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 117 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 118 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 119 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 120 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 121 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 122 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 123 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 124 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 125 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 126 = nosys */
	{ 0, (sy_call_t *)nosys, AUE_NULL, NULL, 0, 0, 0, SY_THR_ABSENT },			/* 127 = nosys */
};
